### PR TITLE
Added HTML5 Security Cheat Sheet

### PR DESCRIPTION
**Pull request by gokulkrishh**
Added HTML5 Security Cheat Sheet to list

### CODE REVIEW

**Comment by logeshpaul** [comment]
@gokulkrishh Thanks for the the contribution :)
1. Can we have a separate preview image for inline display (loads quickly while loading the repo). And suppply the full size image from `downloads` folder. Check HTML5 cheat sheet for reference.
2. [HTML5 tag cheat sheet] - needs to be replaced to HTML security cheatsheet

**Comment by gokulkrishh** [comment]
Sure @logeshpaul will do it.

**Comment by gokulkrishh** [comment]
Its done @logeshpaul. Added preview image in small size.

**Comment by logeshpaul** [comment]
Awesome! Thanks mate :+1:

**Pull request merged**
